
platform :osx, '10.12'
# http://guides.cocoapods.org/using/the-podfile.html
# ignore all warnings from all pods
inhibit_all_warnings!

target 'BeeFun' do
	use_frameworks!
    #UI
   pod 'Sparkle'

#Uti
#pod 'SwiftyUserDefaults', '4.0.0-alpha.1'
#    pod 'GHMarkdownParser'
    pod 'Down'
    pod 'Zip'
    pod 'Fabric'
#    pod 'HotKey'
    pod 'Crashlytics'
	pod 'Alamofire'
    pod 'SnapKit'
    pod "PromiseKit"
    pod 'Moya'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    pod 'CryptoSwift'
    pod 'SwiftyJSON'
    pod 'SwiftyBeaver'
    pod 'SwiftDate'
#	pod 'Bugly'
#    pod 'SwiftyStoreKit'
#    pod 'AVOSCloud'
#   pod 'SwiftLint'
    pod 'SQLite.swift'
#    pod 'ITSwitch'
#    pod 'p2.OAuth2'
    pod 'OAuthSwift', :git => 'https://github.com/OAuthSwift/OAuthSwift', :branch => 'master'
#    pod 'CallbackURLKit'
#    pod 'DJProgressHUD_OSX'
    #加密
#    pod 'CryptoSwift'
#    pod 'ProgressKit'
#    pod 'AudioKit'
#    pod 'SwifterSwift'
#    pod 'KeychainAccess'
#    pod 'SwiftOCR'
#    pod 'FlagKit'
    #动画
#    pod 'YapAnimator'
    pod 'MASPreferences'
    pod 'MASShortcut'
#    pod 'ShortcutRecorder'
    pod 'ReachabilitySwift'
#    pod 'Kanna', :git => 'https://github.com/tid-kijyun/Kanna.git', :branch => 'feature/v4.0.0'
#    pod 'Reveal-SDK', :configurations => ['Debug']
    #    pod 'GodEye', '~> 1.0.0', :configurations => ['Debug']  
end

# 优化编译速度
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Debug'
                config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
            end
        end
    end
end
